# Copyright (c) Facebook, Inc. and its affiliates.
from . import data  # register all new datasets
from . import modeling

# config
from .config import add_cat_seg_config

# dataset loading
from .data.dataset_mappers.detr_panoptic_dataset_mapper import DETRPanopticDatasetMapper
from .data.dataset_mappers.mask_former_panoptic_dataset_mapper import (
    MaskFormerPanopticDatasetMapper,
)
from .data.dataset_mappers.mask_former_semantic_dataset_mapper import (
    MaskFormerSemanticDatasetMapper,
)

# models
from .cat_seg_model import CATSeg
from .test_time_augmentation import SemanticSegmentorWithTTA
from .implicit_fusion_Ver01 import ImplicitFusionCATSegVer01
from .implicit_fusion_Ver01a import ImplicitFusionCATSegVer01a
from .implicit_fusion_Ver01b import ImplicitFusionCATSegVer01b
from .implicit_fusion_Ver02 import ImplicitFusionCATSegVer02
from .implicit_fusion_Ver03 import ImplicitFusionCATSegVer03
from .implicit_fusion_Ver04 import ImplicitFusionCATSegVer04
from .implicit_fusion_Ver05 import ImplicitFusionCATSegVer05
from .implicit_fusion_Ver05a import ImplicitFusionCATSegVer05a
from .implicit_fusion_Ver06 import ImplicitFusionCATSegVer06
from .implicit_fusion_Ver07 import ImplicitFusionCATSegVer07
from .implicit_fusion_Ver08 import ImplicitFusionCATSegVer08
from .implicit_fusion_Ver09 import ImplicitFusionCATSegVer09
from .implicit_fusion_Ver09a import ImplicitFusionCATSegVer09a
from .implicit_fusion_Ver09b import ImplicitFusionCATSegVer09b
from .implicit_fusion_Ver09c import ImplicitFusionCATSegVer09c
from .implicit_fusion_Ver09d import ImplicitFusionCATSegVer09d
from .implicit_fusion_Ver09e import ImplicitFusionCATSegVer09e
from .implicit_fusion_Ver10 import ImplicitFusionCATSegVer10
from .implicit_fusion_Ver11 import ImplicitFusionCATSegVer11
from .implicit_fusion_Ver12 import ImplicitFusionCATSegVer12
from .implicit_fusion_Ver12a import ImplicitFusionCATSegVer12a
from .implicit_fusion_Ver13 import ImplicitFusionCATSegVer13
from .implicit_fusion_Ver14 import ImplicitFusionCATSegVer14
from .implicit_fusion_Ver14a import ImplicitFusionCATSegVer14a
from .implicit_fusion_Ver14b import ImplicitFusionCATSegVer14b
from .implicit_fusion_Ver14c import ImplicitFusionCATSegVer14c
from .implicit_fusion_Ver14d import ImplicitFusionCATSegVer14d
from .implicit_fusion_Ver14e import ImplicitFusionCATSegVer14e
from .implicit_fusion_Ver20 import ImplicitFusionCATSegVer20
from .implicit_fusion_Ver20a import ImplicitFusionCATSegVer20a
from .implicit_fusion_Ver21 import ImplicitFusionCATSegVer21
from .implicit_fusion_Ver22 import ImplicitFusionCATSegVer22
from .implicit_fusion_Ver22a import ImplicitFusionCATSegVer22a
from .implicit_fusion_Ver23 import ImplicitFusionCATSegVer23
from .implicit_fusion_Ver24 import ImplicitFusionCATSegVer24
from .implicit_fusion_Ver24a import ImplicitFusionCATSegVer24a
from .implicit_fusion_Ver25 import ImplicitFusionCATSegVer25
from .implicit_fusion_Ver26 import ImplicitFusionCATSegVer26
from .implicit_fusion_Ver27 import ImplicitFusionCATSegVer27
from .implicit_fusion_Ver28 import ImplicitFusionCATSegVer28
from .implicit_fusion_Ver29 import ImplicitFusionCATSegVer29
from .implicit_fusion_Ver30 import ImplicitFusionCATSegVer30
from .implicit_fusion_Ver31 import ImplicitFusionCATSegVer31

from .vision_transformer import vit_base


# from .vision_transformer import * 
# from .vision_transformer import vits